Adding support for multiple formsets with prefixes
FHBrandenburg/django-bootstrap-dynamic-formsets pull request #6
Opened 2016-09-28 00:32 UTC by MikeSandford

I'm looking this over and I just realized that it's a little ugly; it'll add in a bunch of leading or trailing dashes if you make a form without any prefixes.  I don't think that'll break either the CSS or the javascript, but I honestly don't know.  I can definitely clean up the generated markup but it'll make the code uglier with a lot of {% if formset.prefix %}-{{ formset.prefix }}{% endif %} everywhere instead of just -{{ formset.prefix}}.

2016-10-02 02:06 UTC, MikeSandford commented
Any feedback on the pull request?  Do I need to make the above-stated changes?  Or is what I've already done good enough?

2016-10-02 20:20 UTC, danielw92 commented
Sorry for not getting back to you any sooner.
Your code looks good to me, even though I haven't had the time to actually try it out yet.
Personally, I don't mind the dashes, but I suppose it would a bit cleaner without them. Those conditional statements are also the only way I can think of to accomplish that. So if you don't mind adding those in, please do. I would then merge the PR and release a new build.
Thank you for contributing!

2016-10-07 22:15 UTC, MikeSandford commented
I made the discussed changes and tested it in my local environment; everything still worked.  I'm not going to certify this code as 100% because I haven't tested it without prefixes and there's some chance something could go wrong there.  I just don't have any use cases like that.

2016-10-09 17:57 UTC, danielw92 requested changes
Thanks again for your PR. I came across a few things while testing. One more thing that I or someone else will have to address at some point is that currently, if you have multiple formsets in a page, the javascript code will be inserted multiple times.

2016-10-09 17:57 UTC, danielw92 commented on django_bootstrap_dynamic_formsets/templates/django_bootstrap_dynamic_formsets/dynamic_formsets_js.html
> +                handle: ".sort-handle",
The sort handle also needs the formset-prefix.

2016-10-09 17:57 UTC, danielw92 commented on django_bootstrap_dynamic_formsets/templates/django_bootstrap_dynamic_formsets/dynamic_formsets_js.html
> +            var $sortable = $('#sortable');
I'm not sure if this line could cause problems with multiple formsets in a page. If I'm not mistaken you would have more than one element with this id `sortable` on your page.

2016-10-09 23:50 UTC, MikeSandford commented
Yeah, you're absolutely right about both of those.  I was mostly trying to get this to work in my local environment and once I got that far I called it good enough.

I don't think it makes a lot of sense to worry about inserting the code multiple times for multiple formsets, especially if everything is prefixed properly.  Having multiple copies of very, very similar code will probably be less confusing that figuring out how to inject the code only once and parameterizing it properly.  Of course, I'm biased.

I am going to take a stab at fixing what you've pointed out here this week sometime.

2016-10-10 22:21 UTC, MikeSandford commented
Okay, I've made the changes requested to prefix (or postfix) the id=sortable in the HTML and in the javascript and the sort handle.

I did not address the "preventing this code from being inserted multiple times" issue as I think will be obvious from the code.

2016-10-16 15:56 UTC, danielw92 approved these changes

2016-10-16 15:56 UTC, merged